### ISSUE TITLE
Cannot be build with stack

### ISSUE THREAD

**Issue by dnlkrgr** [thoughtbot/yesod-auth-oauth2#116] opened 2018-10-23 22:56 UTC
When putting this package into my `stack.yaml` as a `extra-deps` I'm getting the following error: "<no location info>: error:
    Could not find module ‘Yesod.Auth.OAuth2.GitHub’
    It is not a module in the current program, or in any known package.
"

**Comment by pbrisbin** [comment] 2018-10-24 11:48
Closing as unable to reproduce. Happy to still follow up and figure out why it's not working for you, but the project indeed builds fine AFAICT, so I suspect it's something else going on.

```
% cat stack.yaml
resolver: lts-12.14
packages:
  - .
extra-deps:
  - hoauth2-1.7.2
  - uri-bytestring-aeson-0.1.0.6
  - yesod-auth-oauth2-0.5.2.0

allow-newer: true
% grep -A 3 '^dependencies:' package.yaml
dependencies:
- base >= 4.7 && < 5
- yesod-auth-oauth2

% grep import src/Lib.hs
import Yesod.Auth.OAuth2.GitHub
% stack build; echo $?
WARNING: Ignoring out of range dependency (allow-newer enabled): exceptions-0.10.0. hoauth2 requires: >=0.8.3 && <0.10
0
```

**Closed by pbrisbin** 2018-10-24 11:48 UTC
